table fact_performance
	lineageTag: a2921b28-1168-4bd0-9369-fc9e172c1447

	column amfi_code
		dataType: int64
		lineageTag: b0b60764-486b-48af-96b3-7d5c858ba727
		sourceColumn: amfi_code

	column scheme_name
		dataType: string
		lineageTag: 86b573c2-a3a4-43c8-a2b0-67e6e21ac936
		sourceColumn: scheme_name

	column fund_house
		dataType: string
		lineageTag: 7f7eec7b-bf37-4ffb-92e3-c1f09e058b13
		sourceColumn: fund_house

	column category
		dataType: string
		lineageTag: 97f62f99-c51e-448b-a5a6-6cda93619c29
		sourceColumn: category

	column plan
		dataType: string
		lineageTag: 149440f0-d558-4a0b-85e9-a0b0c85de478
		sourceColumn: plan

	column return_1yr_pct
		dataType: double
		lineageTag: 8ed648c1-0cba-430d-8127-b66bec0c1ab3
		sourceColumn: return_1yr_pct

	column return_3yr_pct
		dataType: double
		lineageTag: 304f466c-92b7-4842-953c-c26c85a91b02
		sourceColumn: return_3yr_pct

	column return_5yr_pct
		dataType: double
		lineageTag: 2bfa731a-f3b5-4e79-8835-7085a0a9f26d
		sourceColumn: return_5yr_pct

	column benchmark_3yr_pct
		dataType: double
		lineageTag: a9683e01-96aa-4179-8cdf-b5b2a14ab943
		sourceColumn: benchmark_3yr_pct

	column alpha
		dataType: double
		lineageTag: 633650b1-d5c6-4120-ada1-4d438ede4d65
		sourceColumn: alpha

	column beta
		dataType: double
		lineageTag: 527bc579-e753-49fa-8ede-f9720f2f9a4e
		sourceColumn: beta

	column sharpe_ratio
		dataType: double
		lineageTag: 94fb6356-989e-4f46-8de6-e5a916bd83ae
		sourceColumn: sharpe_ratio

	column sortino_ratio
		dataType: double
		lineageTag: 9c83c704-6e9c-45f8-bdc2-59e9253765fc
		sourceColumn: sortino_ratio

	column std_dev_ann_pct
		dataType: double
		lineageTag: 46c20685-0d3f-4b05-99c5-3c51ea373cd8
		sourceColumn: std_dev_ann_pct

	column max_drawdown_pct
		dataType: double
		lineageTag: b5859569-5bd4-4aaa-bcf5-7c487fb829c8
		sourceColumn: max_drawdown_pct

	column aum_crore
		dataType: int64
		lineageTag: 4d330c63-ee80-45a9-a132-643ce405741c
		sourceColumn: aum_crore

	column expense_ratio_pct
		dataType: double
		lineageTag: 46cda0f2-b5d9-4382-bd31-930ade48e96f
		sourceColumn: expense_ratio_pct

	column morningstar_rating
		dataType: int64
		lineageTag: b02c8491-2a12-4567-bcd9-3535c30a39f9
		sourceColumn: morningstar_rating

	column risk_grade
		dataType: string
		lineageTag: 92dcf5f9-00e1-4b5c-b248-4619da5a05df
		sourceColumn: risk_grade

	partition fact_performance-Partition = m
		source =
				let
				    Source = Csv.Document(File.Contents("c:\\Users\\jibum\\OneDrive\\Desktop\\Bluestock Internship\\day 2\\data\\processed\\07_scheme_performance.csv"),[Delimiter=",", Columns=19, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"amfi_code", Int64.Type}, {"return_1yr_pct", type number}, {"return_3yr_pct", type number}, {"return_5yr_pct", type number}, {"benchmark_3yr_pct", type number}, {"alpha", type number}, {"beta", type number}, {"sharpe_ratio", type number}, {"sortino_ratio", type number}, {"std_dev_ann_pct", type number}, {"max_drawdown_pct", type number}, {"aum_crore", Int64.Type}, {"expense_ratio_pct", type number}, {"morningstar_rating", Int64.Type}})
				in
				    #"Changed Type"

