table fact_sip_industry
	lineageTag: d30cb853-db9e-4c4e-86a2-daf30d305dd3

	column month
		dataType: string
		lineageTag: 159d5717-945d-489e-8045-eaabfd2c6c0d
		sourceColumn: month

	column sip_inflow_crore
		dataType: int64
		lineageTag: 7e28b604-0b58-4c2f-a36d-5ddd3d7498ce
		sourceColumn: sip_inflow_crore

	column active_sip_accounts_crore
		dataType: double
		lineageTag: 69cd7262-b9c0-4950-8f67-47526f0cb6a3
		sourceColumn: active_sip_accounts_crore

	column new_sip_accounts_lakh
		dataType: double
		lineageTag: 8e6a02ce-eaaa-445f-9061-69ad6fe5e463
		sourceColumn: new_sip_accounts_lakh

	column sip_aum_lakh_crore
		dataType: double
		lineageTag: af469c8e-8d4b-497a-a150-3d7624b15fc0
		sourceColumn: sip_aum_lakh_crore

	column yoy_growth_pct
		dataType: double
		lineageTag: 4c31298c-e336-4aaa-97a4-833bb470523a
		sourceColumn: yoy_growth_pct

	partition fact_sip_industry-Partition = m
		source =
				let
				    Source = Csv.Document(File.Contents("c:\\Users\\jibum\\OneDrive\\Desktop\\Bluestock Internship\\day 2\\data\\processed\\04_monthly_sip_inflows.csv"),[Delimiter=",", Columns=6, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"sip_inflow_crore", Int64.Type}, {"active_sip_accounts_crore", type number}, {"new_sip_accounts_lakh", type number}, {"sip_aum_lakh_crore", type number}, {"yoy_growth_pct", type number}})
				in
				    #"Changed Type"

