table fact_nav
	lineageTag: 2496561f-525c-4a4a-b773-179f8b37e1f5

	column date
		dataType: string
		lineageTag: 92874c87-8735-44d6-a12d-0cfc779f0148
		sourceColumn: date

	column amfi_code
		dataType: int64
		lineageTag: a44637d0-551b-4414-af9a-72109c425c8b
		sourceColumn: amfi_code

	column nav
		dataType: double
		lineageTag: 92bf114c-0c0b-43f2-957c-3cff7e3ef228
		sourceColumn: nav

	partition fact_nav-Partition = m
		source =
				let
				    Source = Csv.Document(File.Contents("c:\\Users\\jibum\\OneDrive\\Desktop\\Bluestock Internship\\day 2\\data\\processed\\02_nav_history.csv"),[Delimiter=",", Columns=3, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"amfi_code", Int64.Type}, {"nav", type number}})
				in
				    #"Changed Type"

