table fact_portfolio
	lineageTag: 541b5671-6d83-404a-9ba7-cc702ae96270

	column amfi_code
		dataType: int64
		lineageTag: 884f9771-5d7a-42cd-8970-64686e1440a9
		sourceColumn: amfi_code

	column stock_symbol
		dataType: string
		lineageTag: 3b5be07f-e27f-420b-8c4f-50eea9ebd089
		sourceColumn: stock_symbol

	column stock_name
		dataType: string
		lineageTag: 68e95a85-d5cf-4bb5-9bd5-4d9916ae42d8
		sourceColumn: stock_name

	column sector
		dataType: string
		lineageTag: 7d28a222-cd2e-4973-96bb-7aa1e3e1dcc0
		sourceColumn: sector

	column weight_pct
		dataType: double
		lineageTag: 8d4c64b7-78aa-48bb-853a-e84715d0d700
		sourceColumn: weight_pct

	column market_value_cr
		dataType: double
		lineageTag: 8762fb92-45fa-49ad-a2a3-3d802a71af1f
		sourceColumn: market_value_cr

	column current_price_inr
		dataType: double
		lineageTag: 2f19ae3f-5162-4878-b8f7-3c98e7df6c94
		sourceColumn: current_price_inr

	column portfolio_date
		dataType: string
		lineageTag: 510463ff-171e-41fd-b483-40bea97a1dc9
		sourceColumn: portfolio_date

	partition fact_portfolio-Partition = m
		source =
				let
				    Source = Csv.Document(File.Contents("c:\\Users\\jibum\\OneDrive\\Desktop\\Bluestock Internship\\day 2\\data\\processed\\09_portfolio_holdings.csv"),[Delimiter=",", Columns=8, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"amfi_code", Int64.Type}, {"weight_pct", type number}, {"market_value_cr", type number}, {"current_price_inr", type number}})
				in
				    #"Changed Type"

