table fact_aum
	lineageTag: f3e6e3c1-d83c-47b2-af54-fb2d2a463976

	column date
		dataType: string
		lineageTag: 938e3c04-7ab3-4ad8-b2dd-17583d6ad572
		sourceColumn: date

	column fund_house
		dataType: string
		lineageTag: 86ada9c3-2402-4904-ab33-848886f3e40f
		sourceColumn: fund_house

	column aum_lakh_crore
		dataType: double
		lineageTag: 332cd5d2-b973-4666-8fda-76f75d696b55
		sourceColumn: aum_lakh_crore

	column aum_crore
		dataType: int64
		lineageTag: f8cc571b-e5d4-4a14-838d-60b1d39a99ec
		sourceColumn: aum_crore

	column num_schemes
		dataType: int64
		lineageTag: 41da82cb-a1cf-4d2a-b03c-80d56ffd920b
		sourceColumn: num_schemes

	partition fact_aum-Partition = m
		source =
				let
				    Source = Csv.Document(File.Contents("c:\\Users\\jibum\\OneDrive\\Desktop\\Bluestock Internship\\day 2\\data\\processed\\03_aum_by_fund_house.csv"),[Delimiter=",", Columns=5, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"aum_lakh_crore", type number}, {"aum_crore", Int64.Type}, {"num_schemes", Int64.Type}})
				in
				    #"Changed Type"

